-- Supabase 底层是 PostgreSQL（不是 MySQL），以下 SQL 可直接在 Supabase SQL Editor 执行。

create table if not exists public.app_profiles (
  device_id text primary key,
  nickname text not null default '周末旅行者',
  bio text not null default '探索周边，发现精彩',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_favorites (
  id bigint generated by default as identity primary key,
  device_id text not null,
  route_id text not null,
  created_at timestamptz not null default now(),
  unique (device_id, route_id)
);

create index if not exists idx_app_favorites_device_id
  on public.app_favorites(device_id);

create table if not exists public.app_route_history (
  id bigint generated by default as identity primary key,
  device_id text not null,
  route_id text not null,
  city text not null,
  lat double precision,
  lng double precision,
  viewed_at timestamptz not null default now()
);

create index if not exists idx_app_route_history_device_time
  on public.app_route_history(device_id, viewed_at desc);

alter table public.app_profiles enable row level security;
alter table public.app_favorites enable row level security;
alter table public.app_route_history enable row level security;

-- Demo 阶段策略：允许匿名读写。生产环境请改成基于 auth.uid() 的精细策略。
drop policy if exists "Allow read for all (demo)" on public.app_profiles;
create policy "Allow read for all (demo)" on public.app_profiles
  for select using (true);

drop policy if exists "Allow write for all (demo)" on public.app_profiles;
create policy "Allow write for all (demo)" on public.app_profiles
  for all using (true) with check (true);

drop policy if exists "Allow read for all (demo)" on public.app_favorites;
create policy "Allow read for all (demo)" on public.app_favorites
  for select using (true);

drop policy if exists "Allow write for all (demo)" on public.app_favorites;
create policy "Allow write for all (demo)" on public.app_favorites
  for all using (true) with check (true);

drop policy if exists "Allow read for all (demo)" on public.app_route_history;
create policy "Allow read for all (demo)" on public.app_route_history
  for select using (true);

drop policy if exists "Allow write for all (demo)" on public.app_route_history;
create policy "Allow write for all (demo)" on public.app_route_history
  for all using (true) with check (true);
